language: ruby

before_install:
  - ./spec/travis_build.sh > /dev/null 2>&1
  - export LD_FLAGS=-L$HOME/opt/lib
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
  - export CPATH=$CPATH:$HOME/opt/include

rvm:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
env:
  - LIBWEBP_VERSION=0.4.4
  - LIBWEBP_VERSION=1.0.2
  - LIBWEBP_VERSION=1.3.1

cache: bundler
sudo: false
dist: xenial

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: ruby-head
    - rvm: jruby-head
