require 'ffi-compiler/compile_task'

# Detect environment
if RUBY_PLATFORM.include?("darwin")
  # macOS (use brew)
  brew_prefix = `brew --prefix webp`.chomp
  include_path = "#{brew_prefix}/include"
  lib_path     = "#{brew_prefix}/lib"
else
  # Linux
  include_path = "/usr/include"
  lib_path     = "/usr/lib/x86_64-linux-gnu"
end

FFI::Compiler::CompileTask.new('webp_ffi') do |c|
  c.have_header?('stdio.h', include_path)
  c.have_func?('puts')
  c.have_library?('z')

  # webp
  c.have_header?('webp/decode.h', include_path)
  c.have_header?('webp/encode.h', include_path)
  c.have_func?('WebPDecoderConfig')
  c.have_func?('WebPGetInfo')
  c.have_library?('webp', lib_path)

  # other libs
  c.have_library?('png')
  c.have_library?('jpeg')
  c.have_library?('tiff')

  c.ldflags << " -L#{lib_path}"
  c.cflags << " -I#{include_path}"
end
